version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - "env/local.env"
    volumes:
      - ".:/go/src/app"
    links:
      - db
      - db-test
    command: ["go", "run", "server.go"]

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    links:
      - app
    volumes:
      - ".:/go/src/app"
    command: ["go", "run", "gateway/gateway.go", "-endpoint", "app:50051"]

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
    ports:
      - "3306:3306"

  db-test:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_test
    ports:
      - "3340:3306"
